### PR TITLE
Source Formatting

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Review by matuzalemsteles — COMMENTED** [review]
@interaminense @clovisdasilvaneto, we have a lot of code repetition in the files to support other browsers, we can use autoprefixer at compile time to solve these types of problems and to remove redundancy.

**Comment by interaminense** [comment]
Hey @matuzalemsteles,

I also thought in this way I believe we could create a new pull request for this situation. what do you think?

**Comment by clovisdasilvaneto** [comment]
Sound's good, @interaminense, looks like there is some conflicts in your code, can you take a look?

**Comment by matuzalemsteles** [comment]
@interaminense Yes, I think we can architecture better this.

**Comment by interaminense** [comment]
@clovisdasilvaneto conflict solved!

**Comment by clovisdasilvaneto** [comment]
Good, thanks 😄

**Pull request merged**
