### PR TITLE
Adding New Animations and Translation for pt-br 

### PR DESCRIPTION
**Pull request by gabrielsimoest**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
Hey @GtsSim0es thanks for the new animations, I'm just reviewing it now 👍

**Review by clovisdasilvaneto — APPROVED** [review]
Looks lovely ❤️ 👍

**Comment by clovisdasilvaneto** [comment]
@GtsSim0es you can check the new animations out, in our website: https://all-animation.github.io/animations/

**Comment by gabrielsimoest** [comment]
It's amazing! Thanks for merge my commits

**Pull request merged**
